# Generated by Django 5.1.7 on 2025-03-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
    ]
